---
- name: Install kubectl on Ubuntu
  hosts: K8
  become: yes
  tasks:

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name: Download latest stable kubectl version
      shell: |
        curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /tmp/kubectl
      args:
        creates: /tmp/kubectl

    - name: Move kubectl binary to /usr/local/bin
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
        remote_src: yes

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version
      changed_when: false

    - name: Show kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"
